/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ionic-login.module';
import * as i2 from '@angular/common';
import * as i3 from 'angularx-restful/srv/rest.service';
import * as i4 from '@angular/http';
import * as i5 from '@ionic-native/facebook/index';
import * as i6 from '@ionic-native/google-plus/index';
import * as i7 from '../srvs/profile-stabilizer.service';
import * as i8 from '../srvs/ssp.service';
import * as i9 from '../srvs/ysp.service';
import * as i10 from '@ionic-native/native-storage/index';
import * as i11 from '../srvs/ionic-login.service';
import * as i12 from 'angularx-restful/mdl/angularx-restful.module';
export const IonicLoginNgFactory:i0.NgModuleFactory<i1.IonicLogin> = i0.ɵcmf(i1.IonicLogin,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.RestService,
          i3.RestService,[i4.Http]),i0.ɵmpd(4608,i5.Facebook,i5.Facebook,([] as any[])),
          i0.ɵmpd(4608,i6.GooglePlus,i6.GooglePlus,([] as any[])),i0.ɵmpd(4608,i7.ProfileStabilizer,
              i7.ProfileStabilizer,([] as any[])),i0.ɵmpd(4608,i8.Ssp,i8.Ssp,[i3.RestService,
              i5.Facebook,i6.GooglePlus,i7.ProfileStabilizer]),i0.ɵmpd(4608,i9.Ysp,
              i9.Ysp,[i3.RestService]),i0.ɵmpd(4608,i10.NativeStorage,i10.NativeStorage,
              ([] as any[])),i0.ɵmpd(4608,i11.LoginService,i11.LoginService,[i8.Ssp,
              i9.Ysp,i10.NativeStorage]),i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i12.AngularxRestful,i12.AngularxRestful,([] as any[])),
          i0.ɵmpd(512,i1.IonicLogin,i1.IonicLogin,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU2FuZC1NYW4vRGVza3RvcC9jdXRlUHVwcHlQaWNzL215TWRsL21kbHMvaW9uaWMtbG9naW4ubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1NhbmQtTWFuL0Rlc2t0b3AvY3V0ZVB1cHB5UGljcy9teU1kbC9tZGxzL2lvbmljLWxvZ2luLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
